backend:
  name: github
  repo: aastarbuck/ascension
  branch: cms-eval-decap

media_folder: "src/assets/images"
public_folder: "/src/assets/images"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/pages/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
